# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/l7aur/CLionProjects/BMP2JPEG

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/l7aur/CLionProjects/BMP2JPEG

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/l7aur/CLionProjects/BMP2JPEG/CMakeFiles /home/l7aur/CLionProjects/BMP2JPEG//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/l7aur/CLionProjects/BMP2JPEG/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BMP2JPEG

# Build rule for target.
BMP2JPEG: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BMP2JPEG
.PHONY : BMP2JPEG

# fast build rule for target.
BMP2JPEG/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/build
.PHONY : BMP2JPEG/fast

src/BMP_Decoder/BMP.o: src/BMP_Decoder/BMP.cpp.o
.PHONY : src/BMP_Decoder/BMP.o

# target to build an object file
src/BMP_Decoder/BMP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/BMP.cpp.o
.PHONY : src/BMP_Decoder/BMP.cpp.o

src/BMP_Decoder/BMP.i: src/BMP_Decoder/BMP.cpp.i
.PHONY : src/BMP_Decoder/BMP.i

# target to preprocess a source file
src/BMP_Decoder/BMP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/BMP.cpp.i
.PHONY : src/BMP_Decoder/BMP.cpp.i

src/BMP_Decoder/BMP.s: src/BMP_Decoder/BMP.cpp.s
.PHONY : src/BMP_Decoder/BMP.s

# target to generate assembly for a file
src/BMP_Decoder/BMP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/BMP.cpp.s
.PHONY : src/BMP_Decoder/BMP.cpp.s

src/BMP_Decoder/ColorTable.o: src/BMP_Decoder/ColorTable.cpp.o
.PHONY : src/BMP_Decoder/ColorTable.o

# target to build an object file
src/BMP_Decoder/ColorTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/ColorTable.cpp.o
.PHONY : src/BMP_Decoder/ColorTable.cpp.o

src/BMP_Decoder/ColorTable.i: src/BMP_Decoder/ColorTable.cpp.i
.PHONY : src/BMP_Decoder/ColorTable.i

# target to preprocess a source file
src/BMP_Decoder/ColorTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/ColorTable.cpp.i
.PHONY : src/BMP_Decoder/ColorTable.cpp.i

src/BMP_Decoder/ColorTable.s: src/BMP_Decoder/ColorTable.cpp.s
.PHONY : src/BMP_Decoder/ColorTable.s

# target to generate assembly for a file
src/BMP_Decoder/ColorTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/ColorTable.cpp.s
.PHONY : src/BMP_Decoder/ColorTable.cpp.s

src/BMP_Decoder/DIBHeader.o: src/BMP_Decoder/DIBHeader.cpp.o
.PHONY : src/BMP_Decoder/DIBHeader.o

# target to build an object file
src/BMP_Decoder/DIBHeader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/DIBHeader.cpp.o
.PHONY : src/BMP_Decoder/DIBHeader.cpp.o

src/BMP_Decoder/DIBHeader.i: src/BMP_Decoder/DIBHeader.cpp.i
.PHONY : src/BMP_Decoder/DIBHeader.i

# target to preprocess a source file
src/BMP_Decoder/DIBHeader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/DIBHeader.cpp.i
.PHONY : src/BMP_Decoder/DIBHeader.cpp.i

src/BMP_Decoder/DIBHeader.s: src/BMP_Decoder/DIBHeader.cpp.s
.PHONY : src/BMP_Decoder/DIBHeader.s

# target to generate assembly for a file
src/BMP_Decoder/DIBHeader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/DIBHeader.cpp.s
.PHONY : src/BMP_Decoder/DIBHeader.cpp.s

src/BMP_Decoder/ExtraBitMask.o: src/BMP_Decoder/ExtraBitMask.cpp.o
.PHONY : src/BMP_Decoder/ExtraBitMask.o

# target to build an object file
src/BMP_Decoder/ExtraBitMask.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/ExtraBitMask.cpp.o
.PHONY : src/BMP_Decoder/ExtraBitMask.cpp.o

src/BMP_Decoder/ExtraBitMask.i: src/BMP_Decoder/ExtraBitMask.cpp.i
.PHONY : src/BMP_Decoder/ExtraBitMask.i

# target to preprocess a source file
src/BMP_Decoder/ExtraBitMask.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/ExtraBitMask.cpp.i
.PHONY : src/BMP_Decoder/ExtraBitMask.cpp.i

src/BMP_Decoder/ExtraBitMask.s: src/BMP_Decoder/ExtraBitMask.cpp.s
.PHONY : src/BMP_Decoder/ExtraBitMask.s

# target to generate assembly for a file
src/BMP_Decoder/ExtraBitMask.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/ExtraBitMask.cpp.s
.PHONY : src/BMP_Decoder/ExtraBitMask.cpp.s

src/BMP_Decoder/FileHeader.o: src/BMP_Decoder/FileHeader.cpp.o
.PHONY : src/BMP_Decoder/FileHeader.o

# target to build an object file
src/BMP_Decoder/FileHeader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/FileHeader.cpp.o
.PHONY : src/BMP_Decoder/FileHeader.cpp.o

src/BMP_Decoder/FileHeader.i: src/BMP_Decoder/FileHeader.cpp.i
.PHONY : src/BMP_Decoder/FileHeader.i

# target to preprocess a source file
src/BMP_Decoder/FileHeader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/FileHeader.cpp.i
.PHONY : src/BMP_Decoder/FileHeader.cpp.i

src/BMP_Decoder/FileHeader.s: src/BMP_Decoder/FileHeader.cpp.s
.PHONY : src/BMP_Decoder/FileHeader.s

# target to generate assembly for a file
src/BMP_Decoder/FileHeader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/FileHeader.cpp.s
.PHONY : src/BMP_Decoder/FileHeader.cpp.s

src/BMP_Decoder/PixelData.o: src/BMP_Decoder/PixelData.cpp.o
.PHONY : src/BMP_Decoder/PixelData.o

# target to build an object file
src/BMP_Decoder/PixelData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/PixelData.cpp.o
.PHONY : src/BMP_Decoder/PixelData.cpp.o

src/BMP_Decoder/PixelData.i: src/BMP_Decoder/PixelData.cpp.i
.PHONY : src/BMP_Decoder/PixelData.i

# target to preprocess a source file
src/BMP_Decoder/PixelData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/PixelData.cpp.i
.PHONY : src/BMP_Decoder/PixelData.cpp.i

src/BMP_Decoder/PixelData.s: src/BMP_Decoder/PixelData.cpp.s
.PHONY : src/BMP_Decoder/PixelData.s

# target to generate assembly for a file
src/BMP_Decoder/PixelData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/BMP_Decoder/PixelData.cpp.s
.PHONY : src/BMP_Decoder/PixelData.cpp.s

src/JFIF_Encoder/JFIF.o: src/JFIF_Encoder/JFIF.cpp.o
.PHONY : src/JFIF_Encoder/JFIF.o

# target to build an object file
src/JFIF_Encoder/JFIF.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/JFIF_Encoder/JFIF.cpp.o
.PHONY : src/JFIF_Encoder/JFIF.cpp.o

src/JFIF_Encoder/JFIF.i: src/JFIF_Encoder/JFIF.cpp.i
.PHONY : src/JFIF_Encoder/JFIF.i

# target to preprocess a source file
src/JFIF_Encoder/JFIF.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/JFIF_Encoder/JFIF.cpp.i
.PHONY : src/JFIF_Encoder/JFIF.cpp.i

src/JFIF_Encoder/JFIF.s: src/JFIF_Encoder/JFIF.cpp.s
.PHONY : src/JFIF_Encoder/JFIF.s

# target to generate assembly for a file
src/JFIF_Encoder/JFIF.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/JFIF_Encoder/JFIF.cpp.s
.PHONY : src/JFIF_Encoder/JFIF.cpp.s

src/Util/ImageRenderer.o: src/Util/ImageRenderer.cpp.o
.PHONY : src/Util/ImageRenderer.o

# target to build an object file
src/Util/ImageRenderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/Util/ImageRenderer.cpp.o
.PHONY : src/Util/ImageRenderer.cpp.o

src/Util/ImageRenderer.i: src/Util/ImageRenderer.cpp.i
.PHONY : src/Util/ImageRenderer.i

# target to preprocess a source file
src/Util/ImageRenderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/Util/ImageRenderer.cpp.i
.PHONY : src/Util/ImageRenderer.cpp.i

src/Util/ImageRenderer.s: src/Util/ImageRenderer.cpp.s
.PHONY : src/Util/ImageRenderer.s

# target to generate assembly for a file
src/Util/ImageRenderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/Util/ImageRenderer.cpp.s
.PHONY : src/Util/ImageRenderer.cpp.s

src/Util/Mat8x8.o: src/Util/Mat8x8.cpp.o
.PHONY : src/Util/Mat8x8.o

# target to build an object file
src/Util/Mat8x8.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/Util/Mat8x8.cpp.o
.PHONY : src/Util/Mat8x8.cpp.o

src/Util/Mat8x8.i: src/Util/Mat8x8.cpp.i
.PHONY : src/Util/Mat8x8.i

# target to preprocess a source file
src/Util/Mat8x8.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/Util/Mat8x8.cpp.i
.PHONY : src/Util/Mat8x8.cpp.i

src/Util/Mat8x8.s: src/Util/Mat8x8.cpp.s
.PHONY : src/Util/Mat8x8.s

# target to generate assembly for a file
src/Util/Mat8x8.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/Util/Mat8x8.cpp.s
.PHONY : src/Util/Mat8x8.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BMP2JPEG.dir/build.make CMakeFiles/BMP2JPEG.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... BMP2JPEG"
	@echo "... src/BMP_Decoder/BMP.o"
	@echo "... src/BMP_Decoder/BMP.i"
	@echo "... src/BMP_Decoder/BMP.s"
	@echo "... src/BMP_Decoder/ColorTable.o"
	@echo "... src/BMP_Decoder/ColorTable.i"
	@echo "... src/BMP_Decoder/ColorTable.s"
	@echo "... src/BMP_Decoder/DIBHeader.o"
	@echo "... src/BMP_Decoder/DIBHeader.i"
	@echo "... src/BMP_Decoder/DIBHeader.s"
	@echo "... src/BMP_Decoder/ExtraBitMask.o"
	@echo "... src/BMP_Decoder/ExtraBitMask.i"
	@echo "... src/BMP_Decoder/ExtraBitMask.s"
	@echo "... src/BMP_Decoder/FileHeader.o"
	@echo "... src/BMP_Decoder/FileHeader.i"
	@echo "... src/BMP_Decoder/FileHeader.s"
	@echo "... src/BMP_Decoder/PixelData.o"
	@echo "... src/BMP_Decoder/PixelData.i"
	@echo "... src/BMP_Decoder/PixelData.s"
	@echo "... src/JFIF_Encoder/JFIF.o"
	@echo "... src/JFIF_Encoder/JFIF.i"
	@echo "... src/JFIF_Encoder/JFIF.s"
	@echo "... src/Util/ImageRenderer.o"
	@echo "... src/Util/ImageRenderer.i"
	@echo "... src/Util/ImageRenderer.s"
	@echo "... src/Util/Mat8x8.o"
	@echo "... src/Util/Mat8x8.i"
	@echo "... src/Util/Mat8x8.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

